import os

general_path = "./tests/results/"

file_list = [
    "bad_diff_func",
    "bound_loop_with_var",
    "compound_condition",
    "compound_condition_param",
    "compound_condition_param_v2",
    "compound_condition_v2",
    "compound_condition_v3",
    "condcall_one",
    # Decompiler can't handle return 1-liner? "condcall_two",
    "empty",
    "exclusive_ite",
    "exclusive_ite_goal_in_else",
    "goal_diff_func",
    "global_var",
    "global_var_updates",
    "global_var_nongoal",
    "independent_ite",
    "independent_ite_param",
    "input_inside_bound_loop",
    "inter_func_narrow_to_wide_constraint",
    "inter_func_param",
    "inter_func_wide_to_narrow_constraint",
    # Decompiler can't handle return 1-liner? "inter_rv",
    "invalid_compound_condition",
    "invalid_compound_condition_param",
    "invalid_compound_condition_v2",
    "invalid_condition",
    "invalid_inter_func",
    "invalid_nested_conditions",
    "linear_flow",
    "loop_even_odd",
    # Fails on compiler "loop_even_odd_nongoal",
    "multi_call_inter_cond",
    "multi_call_inter_cond_else",
    "multi_call_inter_seq",
    "multiple_ite",
    "multivar_compound_condition",
    "nested_condition",
    "nested_condition_v2",
    "nested_condition_v3",
    "nested_ite_condition",
    "nested_ite_condition_param",
    "nested_ite_condition_param_v2",
    "nested_ite_condition_v2",
    "nested_loop",
    # Not dealing with OO yet "oo_simple_goal",
    # Not dealing with OO yet "oo_simple_nongoal",
    # Not dealing with OO yet "oo_virtual_func_goal",
    # Not dealing with OO yet "oo_virtual_func_nongoal",
    "param_n_var_conpound_condition",
    "rv_cond",
    "rv_same_var",
    "rv_seq",
    "rv_seq_v1",
    "rv_seq_v2",
    # Decompiler can't handle return 1-liner? "seq_call_five",
    # Decompiler can't handle return 1-liner? "seq_call_four",
    # Decompiler can't handle return 1-liner? "seq_call_one",
    # Decompiler can't handle return 1-liner? "seq_call_three",
    # Decompiler can't handle return 1-liner? "seq_call_two",
    "seq_v4",
    "single_condition",
    "single_condition_param",
    "single_condition_param_v2",
    "single_condition_v2",
    "unbound_loop_with_var",
    "var_values",
    "var_values_param"]

for file in file_list:
    file_path = general_path + file + ".ll"
